version: '{build}-{branch}'

os: 'Visual Studio 2015'

environment:
  matrix:
    - ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      GOPATH: c:\gopath
      GOARCH: amd64
      EXTLD: x86_64-w64-mingw32-gcc
    - ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      GOPATH: c:\gopath
      GOARCH: 386
      EXTLD: i686-w64-mingw32-gcc

deploy:
  tag: 'appveyor-test'
  description: ''
  provider: GitHub
  auth_token:
    secure: SZ8sNIW4v/SmMNFdSVfsgRkZQYDqAc5oETCyfLghksY6RC5SGeSnlemE6FQjXVa+
  artifact: /.*\.(exe|sha256sum)/
  draft: true
  prerelease: true
  force_update: true

clone_folder: C:\gopath\src\github.com\square\ghostunnel

before_build:
  # Go paths
  - set PATH=C:\go19\bin;C:\%GOPATH%\bin;%PATH%
  # MSYS paths
  - set PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%
  # Install build deps
  - bash -lc "for n in `seq 1 3`; do pacman --noconfirm -Syyuu && break || sleep 15; done"
  - bash -lc "for n in `seq 1 3`; do pacman --noconfirm -S mingw-w64-%MSYS2_ARCH%-libtool libltdl && break || sleep 15; done"

build_script:
  - git describe > version
  - set /p GIT_VERSION= < version
  - set CGO_ENABLED=0
  - go build -o ghostunnel-%GIT_VERSION%-windows-%GOARCH%-without-pkcs11.exe -ldflags "-w -extldflags \"-static\" -extld=%EXTLD%" -i .
  - sha256sum ghostunnel-%GIT_VERSION%-windows-%GOARCH%-without-pkcs11.exe > ghostunnel-%GIT_VERSION%-windows-%GOARCH%-without-pkcs11.exe.sha256sum
  - appveyor PushArtifact ghostunnel-%GIT_VERSION%-windows-%GOARCH%-without-pkcs11.exe
  - appveyor PushArtifact ghostunnel-%GIT_VERSION%-windows-%GOARCH%-without-pkcs11.exe.sha256sum
  - set CGO_ENABLED=1
  - go build -o ghostunnel-%GIT_VERSION%-windows-%GOARCH%-with-pkcs11.exe -ldflags "-w -extldflags \"-static\" -extld=%EXTLD%" -i .
  - sha256sum ghostunnel-%GIT_VERSION%-windows-%GOARCH%-with-pkcs11.exe > ghostunnel-%GIT_VERSION%-windows-%GOARCH%-with-pkcs11.exe.sha256sum
  - appveyor PushArtifact ghostunnel-%GIT_VERSION%-windows-%GOARCH%-with-pkcs11.exe
  - appveyor PushArtifact ghostunnel-%GIT_VERSION%-windows-%GOARCH%-with-pkcs11.exe.sha256sum
  - go test -v .
